name: CI (macOS)

on:
  workflow_dispatch: # 允许手动运行

permissions:
  contents: read

jobs:
  build-macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 0
    - name: Install dependencies
      run: brew install python3 sdl2
    - name: Build
      env:
        USE_LIBSDL: 1
        TOOLS: 1
      run: make -j2
    - name: Validate
      run: ./mame -validate
    - uses: actions/upload-artifact@main
      with:
        name: mame-macos-${{ github.sha }}
        path: |
          mame
          chdman
          unidasm
        if-no-files-found: error
