name: Compile UI translations

on:
  workflow_dispatch: # 允许手动运行

permissions:
  contents: read

jobs:
  build-language:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 0
    - name: Compile message catalogs
      run: for x in language/*/*.po ; do python scripts/build/msgfmt.py --output-file "`dirname "$x"`/`basename "$x" .po`.mo" "$x" ; done
    - uses: actions/upload-artifact@main
      with:
        name: mame-language-${{ github.sha }}
        path: language/*/*.mo
        if-no-files-found: error
